### ISSUE TITLE
Running jkl should create config file if none exist

### ISSUE THREAD

**Issue by enocom** [bradylove/jkl#2]
After first installing `jkl` and running it, I get this error:

```
failed to read jkl manifest: open /Users/eno/.jkl: no such file or directory
```

**Comment by bradylove** [comment]
If the manifest does not exist, one will be created while running any `jkl` command. The created manifest has an example for `jkl` which is commented out. Easiest way to get started now after installing jkl is to run `jkl edit`.

This was added in 5981751b

**Comment by enocom** [comment]
This is a great improvement. Thanks! 👍
